version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - /data/db/mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    volumes:
      - /data/db/redis
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASS:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gostack_gobarber
      PGDATA: /data/db/postgres
