version: "3"
services:
  mongo:
    image: bitnami/mongodb:latest
    ports:
      - "27017:27017"
    environment:
      MONGODB_USERNAME: gobarber
      MONGODB_PASSWORD: docker
      MONGODB_DATABASE: gobarber

  redis:
    image: bitnami/redis:latest
    volumes:
      - /data/db/redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis

  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_DATABASE: gobarber
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_USERNAME: postgres
